name: Deploy Studio Flow
description: Deploy Studio Flows to a Twilio account ([Documentation](https://github.com/zingdevlimited/studio-flow-actions/blob/v1/README.md#deploy))

inputs:
  CONFIG_PATH:
    required: true
    description: The path to the Studio Configuration file
  TWILIO_API_KEY:
    required: true
    description: The Twilio Api Key
  TWILIO_API_SECRET:
    required: true
    description: The Twilio Api Secret
  COMMIT_MESSAGE:
    required: false
    description: (Optional) Commit message in the Studio Flow revisions
  TOKEN:
    required: false
    description: "A GitHub token with `contents:read` permission (used if required files are not already checked out)"
    default: ${{ github.token }}

runs:
  using: node20
  main: index.js