name: Validate Studio Flow
description: Online Validation of Studio Flow Definitions against the Twilio Flow Validation API. Ensures referenced resources also exist (([Documentation](https://github.com/zingdevlimited/studio-flow-actions/blob/v1/README.md#validate)))

inputs:
  CONFIG_PATH:
    required: true
    description: The path to the Studio Configuration file
  TWILIO_API_KEY:
    required: true
    description: The Twilio Api Key
  TWILIO_API_SECRET:
    required: true
    description: The Twilio Api Secret
  VALIDATE_PREVIOUS_REVISION_USER:
    required: false
    description: Set to `true` to fail the action when it is detected that the previous Studio Flow revision was changed by a different source.
    default: false
  TOKEN:
    required: false
    description: "A GitHub token with `contents:read` permission (used if required files are not already checked out)"
    default: ${{ github.token }}

runs:
  using: node20
  main: index.js