name: Sync Studio Flow
description: Download Studio Flow instances into source control ([Documentation](https://github.com/zingdevlimited/studio-flow-actions/blob/v1/README.md#sync))

inputs:
  CONFIG_PATH:
    required: true
    description: The path to the Studio Configuration file
  TWILIO_API_KEY:
    required: true
    description: The Twilio Api Key
  TWILIO_API_SECRET:
    required: true
    description: The Twilio Api Secret
  ADD_MISSING_DEPLOY_PROPERTIES:
    required: false
    description: |
      Set to **true** to add missing properties required by deployment, by inferring them from sids. Applies to:

      - `send-to-flex` > `attributes` > `workflowName`
      - `send-to-flex` > `attributes` > `channelName`
      - `run-subflow` > `parameters` > `subflowName`
  SAVE_DIAGRAMS_TO_PATH:
    required: false
    description: Directory to save Mermaid diagrams (as SVG files)
  DISABLE_CHECK:
    required: false
    description: Set to **true** to disable the Check action from being ran as part of Sync
  TOKEN:
    required: false
    description: "A GitHub token with `contents:write` and `pullrequests:write` permissions"
    default: ${{ github.token }}

runs:
  using: node20
  main: index.js
